// Copyright © 1996-2018, Valve Corporation, All rights reserved.

#ifndef BASE_INCLUDE_WINDOWS_PRODUCT_VERSION_H_
#define BASE_INCLUDE_WINDOWS_PRODUCT_VERSION_H_

#define HALFLIFE_VER_COMPANYNAME_STR "The Half-Life 2 Authors"
#define HALFLIFE_VER_LEGALCOPYRIGHT_STR \
  "Copyright 1996-2018 " HALFLIFE_VER_COMPANYNAME_STR ". All rights reserved."
#define HALFLIFE_VER_PRODUCTNAME_STR "Half-Life 2"

#ifndef HALFLIFE_STRINGIFY_WORKER
#define HALFLIFE_STRINGIFY_WORKER(text) #text
#endif

#ifndef HALFLIFE_STRINGIFY
#define HALFLIFE_STRINGIFY(text) HALFLIFE_STRINGIFY_WORKER(text)
#endif

// clang-format off
#define HALFLIFE_VER_PRODUCTVERSION_HEADER 2,0,0,0  // NOLINT Version
#define HALFLIFE_VER_PRODUCTVERSION_INFO   2.0.0.0  // NOLINT Version
// clang-format on
#define HALFLIFE_VER_PRODUCTVERSION_INFO_STR \
  HALFLIFE_STRINGIFY(HALFLIFE_VER_PRODUCTVERSION_INFO)

#define HALFLIFE_VER_FILEVERSION_HEADER HALFLIFE_VER_PRODUCTVERSION_HEADER
#define HALFLIFE_VER_FILEVERSION_INFO HALFLIFE_VER_PRODUCTVERSION_INFO
#define HALFLIFE_VER_FILEVERSION_INFO_STR \
  HALFLIFE_STRINGIFY(HALFLIFE_VER_FILEVERSION_INFO)

#define VS_FF_DEBUG 0x00000001L  // From <verrsrc.h>

#ifndef _DEBUG
#define HALFLIFE_VER_FILEFLAGS 0
#else
#define HALFLIFE_VER_FILEFLAGS VS_FF_DEBUG
#endif

#endif  // BASE_INCLUDE_WINDOWS_PRODUCT_VERSION_H_
