// Copyright © 1996-2007, Valve Corporation, All rights reserved.

#if defined(WIN32)
#include "base/include/windows/windows_light.h"

#include <mmreg.h>
#include <mmsystem.h>
#endif

#include "../filesystem_engine.h"
#include "Color.h"
#include "filesystem.h"
#include "mathlib/mathlib.h"
#include "snd_audio_source.h"
#include "snd_channels.h"
#include "snd_convars.h"
#include "snd_dev_common.h"
#include "snd_dev_direct.h"
#include "snd_dev_wave.h"
#include "snd_dev_xaudio.h"
#include "snd_device.h"
#include "snd_env_fx.h"
#include "snd_io.h"
#include "snd_mix_buf.h"
#include "snd_sfx.h"
#include "snd_wave_data.h"
#include "snd_wave_mixer_adpcm.h"
#include "snd_wave_mixer_private.h"
#include "snd_wave_mixer_xma.h"
#include "snd_wave_source.h"
#include "snd_wave_temp.h"
#include "sound.h"
#include "sound_private.h"
#include "soundflags.h"
#include "soundservice.h"
#include "tier0/include/basetypes.h"
#include "tier0/include/commonmacros.h"
#include "tier0/include/dbg.h"
#include "tier0/include/icommandline.h"
#include "tier0/include/platform.h"
#include "tier0/include/vprof.h"
#include "tier1/convar.h"
#include "tier1/strtools.h"
#include "tier2/riff.h"
#include "voice_sound_engine_interface.h"
