// Copyright © 1996-2018, Valve Corporation, All rights reserved.

#ifndef SOURCE_VSTDLIB_VSTDLIB_H_
#define SOURCE_VSTDLIB_VSTDLIB_H_

#include "tier0/include/platform.h"

#ifdef VSTDLIB_DLL_EXPORT
#define VSTDLIB_INTERFACE DLL_EXPORT
#define VSTDLIB_OVERLOAD DLL_GLOBAL_EXPORT
#define VSTDLIB_CLASS DLL_CLASS_EXPORT
#define VSTDLIB_GLOBAL DLL_GLOBAL_EXPORT
#else
#define VSTDLIB_INTERFACE DLL_IMPORT
#define VSTDLIB_OVERLOAD DLL_GLOBAL_IMPORT
#define VSTDLIB_CLASS DLL_CLASS_IMPORT
#define VSTDLIB_GLOBAL DLL_GLOBAL_IMPORT
#endif

#endif  // SOURCE_VSTDLIB_VSTDLIB_H_
